import { ImageSourcePropType } from "react-native";

export const HOME_LIST = [
  {
    id: 1,
    name: "Airbnb",
    description: "Main Search component\nWhere to - When - Who",
    screen: "Airbnb",
    image: require("@assets/screenshots/1.png"),
  },
  {
    id: 2,
    name: "iOS Shutdown",
    description: "iOS progresive shutdown animation\nAnimated text color",
    screen: "ShutdownIOS",
    image: require("@assets/screenshots/2.png"),
  },
  {
    id: 3,
    name: "iOS NFC Reader",
    description: "iOS NFC payment reader\nShadow like effect",
    screen: "NFCReader",
    image: require("@assets/screenshots/3.png"),
    isDark: true,
  },
  {
    id: 4,
    name: "iOS Search Move",
    description: "iOS search bar animation",
    screen: "TranslateSearchIOS",
    image: require("@assets/screenshots/4.png"),
  },
  {
    id: 5,
    name: "Circular Animated Text",
    description: "Animated text in circular shape",
    screen: "CircularAnimatedText",
    image: require("@assets/screenshots/5.png"),
  },
  {
    id: 6,
    name: "Parallax List",
    description: "Parallax effect\nBlurred background",
    screen: "Parallax",
    image: require("@assets/screenshots/6.png"),
    isDark: true,
  },
  {
    id: 7,
    name: "Double List",
    description: "Double scrolling effect\nScroll one list reveals the other",
    screen: "DoubleList",
    image: require("@assets/screenshots/7.png"),
  },
  {
    id: 8,
    name: "Gallery List",
    description: "Animated gallery with elements interpolation",
    screen: "GalleryList",
    image: require("@assets/screenshots/8.png"),
  },
  {
    id: 9,
    name: "Fade Item List",
    description: "Fade in/out effect on scroll",
    screen: "FadeItem",
    image: require("@assets/screenshots/9.png"),
  },
  {
    id: 10,
    name: "Product List",
    description: "Animated product list with custom gestures",
    screen: "ProductList",
    image: require("@assets/screenshots/11.png"),
  },
  {
    id: 11,
    name: "Enriched Chat",
    description: "Fully responsive chat\nEmoji reactions",
    screen: "Chat",
    image: require("@assets/screenshots/10.png"),
  },
  {
    id: 12,
    name: "Screen Transitions",
    description: "Screen transitions on an education template",
    screen: "ScreenTransition",
    image: require("@assets/screenshots/12.png"),
  },
  {
    id: 13,
    name: "Task Calendar",
    description: "Strip calendar\nAnimated task list",
    screen: "TaskCalendar",
    image: require("@assets/screenshots/13.png"),
  },
  {
    id: 14,
    name: "Bank Template",
    description: "Template for banking app\nShadows & Animated gradient effect",
    screen: "BankStack",
    image: require("@assets/screenshots/14.png"),
  },
  {
    id: 15,
    name: "Line & Pie Chart",
    description: "Fully customizable charts\nGestures support",
    screen: "LinePieCharts",
    image: require("@assets/screenshots/15.png"),
  },
  {
    id: 16,
    name: "Group & Stack Chart",
    description: "Charts with tooltips",
    screen: "GroupStackCharts",
    image: require("@assets/screenshots/16.png"),
  },
  {
    id: 17,
    name: "Roulette",
    description: "Spinning wheel\nReward animation",
    screen: "Lottery",
    image: require("@assets/screenshots/17.png"),
  },
  {
    id: 18,
    name: "Navbar with Indicator",
    description: "Navbar with adaptive indicator",
    screen: "ListWithIndicator",
    image: require("@assets/screenshots/18.png"),
  },
  {
    id: 19,
    name: "Drawer - Corner Transition",
    description: "High end drawer\nView manipulation",
    screen: "CustomDrawer",
    image: require("@assets/screenshots/19.png"),
    isDark: true,
  },
  {
    id: 20,
    name: "Drawer - Window Transition",
    description: "Side by side drawer",
    screen: "DrawerInterpolate",
    image: require("@assets/screenshots/20.png"),
  },
  {
    id: 21,
    name: "Progress Bar",
    description: "Classic animated progre",
    screen: "Progress",
    image: require("@assets/screenshots/21.png"),
  },
  {
    id: 22,
    name: "Dancing Dots",
    description: "Dots moving while loading",
    screen: "DotLoader",
    image: require("@assets/screenshots/22.png"),
  },
  {
    id: 23,
    name: "Floating to Modal",
    description: "Circle to modal shape transition",
    screen: "Floating",
    image: require("@assets/screenshots/23.png"),
  },
  {
    id: 24,
    name: "Floating to Actions",
    description: "Menu presenation with floating action",
    screen: "FloatingActions",
    image: require("@assets/screenshots/24.png"),
  },
  {
    id: 25,
    name: "Floating to Side Actions",
    description: "Side menu with floating action",
    screen: "AddButtonMove",
    image: require("@assets/screenshots/25.png"),
  },
  {
    id: 26,
    name: "Pin Code",
    description: "Animated Pin like validaiton",
    screen: "PinCode",
    image: require("@assets/screenshots/26.png"),
    isDark: true,
  },
  {
    id: 27,
    name: "Switches",
    description: "3 different ways to present a toggler",
    screen: "Togglers",
    image: require("@assets/screenshots/27.png"),
  },
  {
    id: 28,
    name: "Sliders",
    description: "3 different ways to present a slider",
    screen: "ValuePickers",
    image: require("@assets/screenshots/28.png"),
  },
  {
    id: 29,
    name: "Custom Scroll Bar",
    description: "A better scroll indicator with fade in/out effect",
    screen: "VerticalScrollBar",
    image: require("@assets/screenshots/29.png"),
    isDark: true,
  },
  {
    id: 30,
    name: "Gesture Counter",
    description: "Bounce effect & Gesture down to reset counter",
    screen: "GestureCounter",
    image: require("@assets/screenshots/30.png"),
    isDark: true,
  },
  {
    id: 31,
    name: "Like Interaction",
    description: "Moving avatarson like / dislike action",
    screen: "LikeInteraction",
    image: require("@assets/screenshots/31.png"),
  },
];

export type HomeListItem = {
  id: number;
  name: string;
  description: string;
  image: ImageSourcePropType;
  isDark?: undefined;
};
